dependencies:
  - name: finrem-ns
    version: ~0.0.4
    repository: '@hmctspublic'
  - name: finrem-ps
    version: ~0.0.2
    repository: '@hmctspublic'
#  - name: postgresql
#    version: ~5.3.0
#    repository: '@stable'
